version: "3.7"

services:
  haproxy:
    container_name: haproxy
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy.cfg:ro
    ports:
      - "80:80"

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    ports:
      - '9100:9100'

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - .:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3000:3000'