{
 "title": "Highload HW3",
 "panels": [
  {
   "title": "CPU Summary (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"vr-1-server\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"vr-2-server\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"vr-3-server\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"vr-balancer-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS Summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"vr-1-backend\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "irate(hits_counter{job=\"vr-2-backend\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "irate(hits_counter{job=\"vr-3-backend\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Balancer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"vr-balancer-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "CPU vr-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"vr-1-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS vr-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"vr-1-backend\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU vr-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"vr-2-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS vr-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"vr-2-backend\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU vr-3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"vr-3-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS vr-3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"vr-3-backend\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}